#!/bin/bash
HOST="127.0.0.1:7878"
OUTPUT="test_output.txt"

echo "BASIC GET TEST" > $OUTPUT
curl -s -i $HOST >> $OUTPUT

echo "BASIC ECHO TEST" >> $OUTPUT
curl -s $HOST/api/echo >> $OUTPUT

echo "QUERY TEST" >> $OUTPUT
curl -s "$HOST/api/echo?first-query=first-value&second_query" >> $OUTPUT

echo "PROBLEMATIC CHARACTERS IN URL" >> $OUTPUT
curl -s "$HOST/api/echo/\`1234567890-=~!@$%^&*_+\\|;':\",./<>{()}?[]" >> $OUTPUT

echo "PROBLEMATIC CHARACTERS URL PERCENT-ENCODED" >> $OUTPUT
curl -s "$HOST/api/echo/%601234567890-%3D~!%40%23%24%25%5E%26*()_%2B%5B%5D%5C%7B%7D%7C%3B'%3A%22%2C.%2F%3C%3E%3F" >> $OUTPUT

echo "PROBLEMATIC CHARACTERS IN QUERY" >> $OUTPUT
curl -s "$HOST/api/echo?query-1=\`1234567890-=~!@{$%}^&*_+\\()|;':\",./<>=second-value[]" >> $OUTPUT

echo "MULTIPLE QUERY DELIMITERS" >> $OUTPUT
curl -s "$HOST/api/echo?query-1=test?query-2=test2" >> $OUTPUT

echo "PROBLEMATIC CHARACTERS IN QUERY URL PERCENT-ENCODED" >> $OUTPUT
curl -s "$HOST/api/echo?%601234567890-%3D~!%40%23%24%25%5E%26*()_%2B%5B%5D%5C%7B%7D%7C%3B'%3A%22%2C.%2F%3C%3E%3F" >> $OUTPUT

echo "DATA INCLUDED IN BODY" >> $OUTPUT
curl -s $HOST/api/echo --data "Hello World!" >> $OUTPUT

diff $OUTPUT correct_output.txt
# echo "PDF INCLUDED IN BODY ... not implemented yet"

#TODO Always need more tests